//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3.GenerateNumber {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenerateNumber.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerateNumber", ReplyAction="http://tempuri.org/IService1/GenerateNumberResponse")]
        A3.GenerateNumber.GenerateNumberResponse GenerateNumber(A3.GenerateNumber.GenerateNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerateNumber", ReplyAction="http://tempuri.org/IService1/GenerateNumberResponse")]
        System.Threading.Tasks.Task<A3.GenerateNumber.GenerateNumberResponse> GenerateNumberAsync(A3.GenerateNumber.GenerateNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerateNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int lower;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int upper;
        
        public GenerateNumberRequest() {
        }
        
        public GenerateNumberRequest(int lower, int upper) {
            this.lower = lower;
            this.upper = upper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerateNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GenerateNumberResult;
        
        public GenerateNumberResponse() {
        }
        
        public GenerateNumberResponse(int GenerateNumberResult) {
            this.GenerateNumberResult = GenerateNumberResult;
        }
    }
}
